controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
  path: /login
  controller: App\Controller\AuthController::index

home:
  path: /
  controller: App\Controller\HomeController::index
